In [ ]:
import pandas as pd

df=pd.read_csv("/content/kidney_disease.csv")

In [ ]:
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [ ]:
df.isnull().any()

id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['pcc']=le.fit_transform(df['pcc'])
df['rbc']=le.fit_transform(df['rbc'])
df['pc']=le.fit_transform(df['pc'])
df['ba']=le.fit_transform(df['ba'])
df['rc']=le.fit_transform(df['rc'])
df['htn']=le.fit_transform(df['htn'])
df['dm']=le.fit_transform(df['dm'])
df['cad']=le.fit_transform(df['cad'])
df['appet']=le.fit_transform(df['appet'])
df['pe']=le.fit_transform(df['pe'])
df['ane']=le.fit_transform(df['ane'])
df['classification']=le.fit_transform(df['classification'])

In [ ]:
df['age'].fillna(df['age'].mode().iloc[0], inplace=True)
df['bp'].fillna(df['bp'].mode().iloc[0], inplace=True)
df['sg'].fillna(df['sg'].mode().iloc[0], inplace=True)
df['al'].fillna(df['al'].mode().iloc[0], inplace=True)

In [ ]:
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,2,1,0,0,...,44,7800,34,1,4,1,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,2,1,0,0,...,38,6000,49,0,3,1,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,1,1,0,0,...,31,7500,49,0,4,1,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,...,32,6700,19,1,3,1,1,1,1,0
4,4,51.0,80.0,1.010,2.0,0.0,1,1,0,0,...,35,7300,27,0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,1,1,0,0,...,47,6700,30,0,3,1,0,0,0,2
396,396,42.0,70.0,1.025,0.0,0.0,1,1,0,0,...,54,7800,44,0,3,1,0,0,0,2
397,397,12.0,80.0,1.020,0.0,0.0,1,1,0,0,...,49,6600,36,0,3,1,0,0,0,2
398,398,17.0,60.0,1.025,0.0,0.0,1,1,0,0,...,51,7200,41,0,3,1,0,0,0,2
399,399,58.0,80.0,1.025,0.0,0.0,1,1,0,0,...,53,6800,43,0,3,1,0,0,0,2

In [ ]:
df.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                 True
rbc               False
pc                False
pcc               False
ba                False
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [ ]:
df['su'].fillna(df['su'].mode().iloc[0], inplace=True)
df['bgr'].fillna(df['bgr'].mode().iloc[0], inplace=True)
df['bu'].fillna(df['bu'].mode().iloc[0], inplace=True)
df['sc'].fillna(df['sc'].mode().iloc[0], inplace=True)
df['sod'].fillna(df['sod'].mode().iloc[0], inplace=True)
df['pot'].fillna(df['pot'].mode().iloc[0], inplace=True)
df['hemo'].fillna(df['hemo'].mode().iloc[0], inplace=True)
df['pcv'].fillna(df['pcv'].mode().iloc[0], inplace=True)
df['wc'].fillna(df['wc'].mode().iloc[0], inplace=True)

In [ ]:
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,2,1,0,0,...,44,7800,34,1,4,1,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,2,1,0,0,...,38,6000,49,0,3,1,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,1,1,0,0,...,31,7500,49,0,4,1,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,...,32,6700,19,1,3,1,1,1,1,0
4,4,51.0,80.0,1.010,2.0,0.0,1,1,0,0,...,35,7300,27,0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,1,1,0,0,...,47,6700,30,0,3,1,0,0,0,2
396,396,42.0,70.0,1.025,0.0,0.0,1,1,0,0,...,54,7800,44,0,3,1,0,0,0,2
397,397,12.0,80.0,1.020,0.0,0.0,1,1,0,0,...,49,6600,36,0,3,1,0,0,0,2
398,398,17.0,60.0,1.025,0.0,0.0,1,1,0,0,...,51,7200,41,0,3,1,0,0,0,2
399,399,58.0,80.0,1.025,0.0,0.0,1,1,0,0,...,53,6800,43,0,3,1,0,0,0,2

In [ ]:
df.describe

<bound method NDFrame.describe of       id   age    bp     sg   al   su  rbc  pc  pcc  ba  ...  pcv    wc  rc  \
0      0  48.0  80.0  1.020  1.0  0.0    2   1    0   0  ...   44  7800  34
1      1   7.0  50.0  1.020  4.0  0.0    2   1    0   0  ...   38  6000  49
2      2  62.0  80.0  1.010  2.0  3.0    1   1    0   0  ...   31  7500  49
3      3  48.0  70.0  1.005  4.0  0.0    1   0    1   0  ...   32  6700  19
4      4  51.0  80.0  1.010  2.0  0.0    1   1    0   0  ...   35  7300  27
..   ...   ...   ...    ...  ...  ...  ...  ..  ...  ..  ...  ...   ...  ..
395  395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  ...   47  6700  30
396  396  42.0  70.0  1.025  0.0  0.0    1   1    0   0  ...   54  7800  44
397  397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  ...   49  6600  36
398  398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  ...   51  7200  41
399  399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  ...   53  6800  43

     htn  dm  cad appet pe  ane  classification
0      1   4    1     0  0    0               0
1      0   3    1     0  0    0               0
2      0   4    1     1  0    1               0
3      1   3    1     1  1    1               0
4      0   3    1     0  0    0               0
..   ...  ..  ...   ... ..  ...             ...
395    0   3    1     0  0    0               2
396    0   3    1     0  0    0               2
397    0   3    1     0  0    0               2
398    0   3    1     0  0    0               2
399    0   3    1     0  0    0               2

[400 rows x 26 columns]>

In [ ]:
df['pcv'] = pd.to_numeric(df['pcv'], errors='coerce')
df['wc'] = pd.to_numeric(df['wc'], errors='coerce')
df['pcv'].fillna(df['pcv'].mode().iloc[0], inplace=True)
df['wc'].fillna(df['wc'].mode().iloc[0], inplace=True)

from sklearn.preprocessing import MinMaxScaler,StandardScaler
attributes_to_normalize = ['wc','rc','pcv']

# Min-Max Scaling
min_max_scaler = MinMaxScaler()
df[attributes_to_normalize] = min_max_scaler.fit_transform(df[attributes_to_normalize])

# Z-score (Standardization)
z_score_scaler = StandardScaler()
df[attributes_to_normalize] = z_score_scaler.fit_transform(df[attributes_to_normalize])

In [ ]:
df.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [ ]:
x=df.iloc[:,:25]
y=df['classification']

In [ ]:
df.dtypes

id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                 int64
pc                  int64
pcc                 int64
ba                  int64
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv               float64
wc                float64
rc                float64
htn                 int64
dm                  int64
cad                 int64
appet               int64
pe                  int64
ane                 int64
classification      int64
dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 25,random_state = 46)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc_knn = round(accuracy_score(y_pred,y_test), 2) * 100
print("Accuracy :" ,acc_knn)

Accuracy : 96.0